import { NftAssets } from '../hooks/nft/useFetchAssets'

export type VestNFT = {
  attributes: string
  levelLong: string
  levelShort: string
  displayName: string
  bestCost: number
  image: string
}

type VestNFTs = {
  holder: Array<VestNFT>
  referral: Array<VestNFT>
  volunteer: Array<VestNFT>
  governance: Array<VestNFT>
  timestamp: Array<VestNFT>
  game: Array<VestNFT>
}

export const VestNFTs: VestNFTs = {
  holder: [
    {
      attributes: 'Holder',
      levelLong: 'Pirates',
      levelShort: '(P1)',
      displayName: 'Usopp',
      bestCost: 100,
      image: 'vestnft.png',
    },
    {
      attributes: 'Holder',
      levelLong: 'General',
      levelShort: '(G1)',
      displayName: 'Ace',
      bestCost: 1000,
      image: 'vestnft.png',
    },
    {
      attributes: 'Holder',
      levelLong: 'King',
      levelShort: '(K1)',
      displayName: 'Luffy',
      bestCost: 10000,
      image: 'vestnft.png',
    },
  ],
  referral: [
    {
      attributes: 'Referral',
      levelLong: 'Pirates',
      levelShort: '(P1)',
      displayName: 'Alvida',
      bestCost: 100,
      image: 'vestnft.png',
    },
    {
      attributes: 'Referral',
      levelLong: 'General',
      levelShort: '(G1)',
      displayName: 'Smoker',
      bestCost: 1000,
      image: 'vestnft.png',
    },
    {
      attributes: 'Referral',
      levelLong: 'King',
      levelShort: '(K1)',
      displayName: 'Kuzan',
      bestCost: 10000,
      image: 'vestnft.png',
    },
  ],
  volunteer: [
    {
      attributes: 'Volunteer',
      levelLong: 'Pirates',
      levelShort: '(P1)',
      displayName: 'Inazuma',
      bestCost: 100,
      image: 'vestnft.png',
    },
    {
      attributes: 'Volunteer',
      levelLong: 'General',
      levelShort: '(G1)',
      displayName: 'Koala',
      bestCost: 1000,
      image: 'vestnft.png',
    },
    {
      attributes: 'Volunteer',
      levelLong: 'King',
      levelShort: '(K1)',
      displayName: 'Monkey D. Dragon',
      bestCost: 10000,
      image: 'vestnft.png',
    },
  ],
  governance: [
    {
      attributes: 'Governance',
      levelLong: 'Pirates',
      levelShort: '(P1)',
      displayName: 'Coupon',
      bestCost: 100,
      image: 'vestnft.png',
    },
    {
      attributes: 'Governance',
      levelLong: 'General',
      levelShort: '(G1)',
      displayName: 'Book',
      bestCost: 1000,
      image: 'vestnft.png',
    },
    {
      attributes: 'Governance',
      levelLong: 'King',
      levelShort: '(K1)',
      displayName: 'Medal',
      bestCost: 10000,
      image: 'vestnft.png',
    },
  ],
  timestamp: [
    {
      attributes: 'Day',
      levelLong: 'Pirates',
      levelShort: '(P1)',
      displayName: 'Pirate',
      bestCost: 100,
      image: 'vestnft.png',
    },
    {
      attributes: 'Month',
      levelLong: 'General',
      levelShort: '(G1)',
      displayName: 'Yonko',
      bestCost: 1000,
      image: 'vestnft.png',
    },
    {
      attributes: 'Year',
      levelLong: 'King',
      levelShort: '(K1)',
      displayName: 'One Piece',
      bestCost: 10000,
      image: 'vestnft.png',
    },
  ],
  game: [
    {
      attributes: 'Raffle',
      levelLong: 'Pirates',
      levelShort: '(P1)',
      displayName: 'Smoke Fruit',
      bestCost: 100,
      image: 'vestnft.png',
    },
    {
      attributes: 'Raffle',
      levelLong: 'General',
      levelShort: '(G1)',
      displayName: 'Sand-Sand Fruit',
      bestCost: 1000,
      image: 'vestnft.png',
    },
    {
      attributes: 'Raffle',
      levelLong: 'King',
      levelShort: '(K1)',
      displayName: 'Mera-Mera Fruit',
      bestCost: 10000,
      image: 'vestnft.png',
    },
  ],
}

export const VestNFTAddress = '0xdcf2a17bf95840bbe513ce2d9030bb03191570cf'

export const VestNFTList: Array<NftAssets> = [
  {
    id: 1,
    token_id: 1,
    background_color: '#9A7A31',
    image_url: 'local::usopp.png',
    image_preview_url: null,
    image_thumbnail_url: null,
    image_original_url: null,
    name: 'Usopp',
    description: 'Usopp',
    asset_contract: {
      address: '0xdcf2a17bf95840bbe513ce2d9030bb03191570cf',
      name: 'Meme',
      symbol: 'MEME',
    },
    decimals: null,
    traits: [
      {
        trait_type: 'Level',
        value: 1,
        display_type: null,
        max_value: null,
        trait_count: 0,
        order: null,
      },
      {
        trait_type: 'Type',
        value: 'identity',
        display_type: null,
        max_value: null,
        trait_count: 4,
        order: null,
      },
      {
        trait_type: 'Vest Value',
        value: '100',
        display_type: null,
        max_value: null,
        trait_count: 1,
        order: null,
      },
    ],
  },
  {
    id: 2,
    token_id: 2,
    background_color: '#CD3156',
    image_url: 'local::ace.png',
    image_preview_url: null,
    image_thumbnail_url: null,
    image_original_url: null,
    name: 'Portgas D Ace',
    description: 'Portgas D. Ace',
    asset_contract: {
      address: '0xdcf2a17bf95840bbe513ce2d9030bb03191570cf',
      name: 'Meme',
      symbol: 'MEME',
    },
    decimals: null,
    traits: [
      {
        trait_type: 'Level',
        value: 2,
        display_type: null,
        max_value: null,
        trait_count: 0,
        order: null,
      },
      {
        trait_type: 'Type',
        value: 'identity',
        display_type: null,
        max_value: null,
        trait_count: 4,
        order: null,
      },
      {
        trait_type: 'Vest Value',
        value: '1000',
        display_type: null,
        max_value: null,
        trait_count: 1,
        order: null,
      },
    ],
  },
  {
    id: 3,
    token_id: 3,
    background_color: '#C72E22',
    image_url: 'local::luffy.png',
    image_preview_url: null,
    image_thumbnail_url: null,
    image_original_url: null,
    name: 'Monkey D. Luffy',
    description: 'Monkey D. Luffy',
    asset_contract: {
      address: '0xdcf2a17bf95840bbe513ce2d9030bb03191570cf',
      name: 'Meme',
      symbol: 'MEME',
    },
    decimals: null,
    traits: [
      {
        trait_type: 'Level',
        value: 3,
        display_type: null,
        max_value: null,
        trait_count: 0,
        order: null,
      },
      {
        trait_type: 'Type',
        value: 'identity',
        display_type: null,
        max_value: null,
        trait_count: 4,
        order: null,
      },
      {
        trait_type: 'Vest Value',
        value: '10000',
        display_type: null,
        max_value: null,
        trait_count: 1,
        order: null,
      },
    ],
  },
  {
    id: 4,
    token_id: 4,
    background_color: '#9A7B2F',
    image_url: 'local::tashigi.png',
    image_preview_url: null,
    image_thumbnail_url: null,
    image_original_url: null,
    name: 'Tashigi',
    description: 'Tashigi',
    asset_contract: {
      address: '0xdcf2a17bf95840bbe513ce2d9030bb03191570cf',
      name: 'Meme',
      symbol: 'MEME',
    },
    decimals: null,
    traits: [
      {
        trait_type: 'Level',
        value: 1,
        display_type: null,
        max_value: null,
        trait_count: 0,
        order: null,
      },
      {
        trait_type: 'Type',
        value: 'referral',
        display_type: null,
        max_value: null,
        trait_count: 4,
        order: null,
      },
      {
        trait_type: 'Vest Value',
        value: '100',
        display_type: null,
        max_value: null,
        trait_count: 1,
        order: null,
      },
    ],
  },
  {
    id: 5,
    token_id: 5,
    background_color: '#1CA1B4',
    image_url: 'local::smoker.png',
    image_preview_url: null,
    image_thumbnail_url: null,
    image_original_url: null,
    name: 'Smoker',
    description: 'Smoker',
    asset_contract: {
      address: '0xdcf2a17bf95840bbe513ce2d9030bb03191570cf',
      name: 'Meme',
      symbol: 'MEME',
    },
    decimals: null,
    traits: [
      {
        trait_type: 'Level',
        value: 2,
        display_type: null,
        max_value: null,
        trait_count: 0,
        order: null,
      },
      {
        trait_type: 'Type',
        value: 'referral',
        display_type: null,
        max_value: null,
        trait_count: 4,
        order: null,
      },
      {
        trait_type: 'Vest Value',
        value: '1000',
        display_type: null,
        max_value: null,
        trait_count: 1,
        order: null,
      },
    ],
  },
  {
    id: 6,
    token_id: 6,
    background_color: '#6947C4',
    image_url: 'local::kuzan.png',
    image_preview_url: null,
    image_thumbnail_url: null,
    image_original_url: null,
    name: 'Kuzan',
    description: 'Kuzan',
    asset_contract: {
      address: '0xdcf2a17bf95840bbe513ce2d9030bb03191570cf',
      name: 'Meme',
      symbol: 'MEME',
    },
    decimals: null,
    traits: [
      {
        trait_type: 'Level',
        value: 3,
        display_type: null,
        max_value: null,
        trait_count: 0,
        order: null,
      },
      {
        trait_type: 'Type',
        value: 'referral',
        display_type: null,
        max_value: null,
        trait_count: 4,
        order: null,
      },
      {
        trait_type: 'Vest Value',
        value: '10000',
        display_type: null,
        max_value: null,
        trait_count: 1,
        order: null,
      },
    ],
  },
  {
    id: 7,
    token_id: 7,
    background_color: '#6b57d0',
    image_url: 'local::ivankov.png',
    image_preview_url: null,
    image_thumbnail_url: null,
    image_original_url: null,
    name: 'Emporio Ivankov',
    description: 'Emporio Ivankov',
    asset_contract: {
      address: '0xdcf2a17bf95840bbe513ce2d9030bb03191570cf',
      name: 'Meme',
      symbol: 'MEME',
    },
    decimals: null,
    traits: [
      {
        trait_type: 'Level',
        value: 1,
        display_type: null,
        max_value: null,
        trait_count: 0,
        order: null,
      },
      {
        trait_type: 'Type',
        value: 'volunteer',
        display_type: null,
        max_value: null,
        trait_count: 4,
        order: null,
      },
      {
        trait_type: 'Vest Value',
        value: '100',
        display_type: null,
        max_value: null,
        trait_count: 1,
        order: null,
      },
    ],
  },
  {
    id: 8,
    token_id: 8,
    background_color: '#ae608b',
    image_url: 'local::koala.png',
    image_preview_url: null,
    image_thumbnail_url: null,
    image_original_url: null,
    name: 'Koala',
    description: 'Koala',
    asset_contract: {
      address: '0xdcf2a17bf95840bbe513ce2d9030bb03191570cf',
      name: 'Meme',
      symbol: 'MEME',
    },
    decimals: null,
    traits: [
      {
        trait_type: 'Level',
        value: 2,
        display_type: null,
        max_value: null,
        trait_count: 0,
        order: null,
      },
      {
        trait_type: 'Type',
        value: 'volunteer',
        display_type: null,
        max_value: null,
        trait_count: 4,
        order: null,
      },
      {
        trait_type: 'Vest Value',
        value: '1000',
        display_type: null,
        max_value: null,
        trait_count: 1,
        order: null,
      },
    ],
  },
  {
    id: 9,
    token_id: 9,
    background_color: '#4d7c3b',
    image_url: 'local::md-dragon.png',
    image_preview_url: null,
    image_thumbnail_url: null,
    image_original_url: null,
    name: 'Monkey D. Dragon',
    description: 'Monkey D. Dragon',
    asset_contract: {
      address: '0xdcf2a17bf95840bbe513ce2d9030bb03191570cf',
      name: 'Meme',
      symbol: 'MEME',
    },
    decimals: null,
    traits: [
      {
        trait_type: 'Level',
        value: 3,
        display_type: null,
        max_value: null,
        trait_count: 0,
        order: null,
      },
      {
        trait_type: 'Type',
        value: 'volunteer',
        display_type: null,
        max_value: null,
        trait_count: 4,
        order: null,
      },
      {
        trait_type: 'Vest Value',
        value: '10000',
        display_type: null,
        max_value: null,
        trait_count: 1,
        order: null,
      },
    ],
  },
  {
    id: 10,
    token_id: 10,
    background_color: '#7f715e',
    image_url: 'local::coupon.png',
    image_preview_url: null,
    image_thumbnail_url: null,
    image_original_url: null,
    name: 'Coupon',
    description: 'Coupon',
    asset_contract: {
      address: '0xdcf2a17bf95840bbe513ce2d9030bb03191570cf',
      name: 'Meme',
      symbol: 'MEME',
    },
    decimals: null,
    traits: [
      {
        trait_type: 'Level',
        value: 1,
        display_type: null,
        max_value: null,
        trait_count: 0,
        order: null,
      },
      {
        trait_type: 'Type',
        value: 'governance',
        display_type: null,
        max_value: null,
        trait_count: 4,
        order: null,
      },
      {
        trait_type: 'Vest Value',
        value: '100',
        display_type: null,
        max_value: null,
        trait_count: 1,
        order: null,
      },
    ],
  },
  {
    id: 11,
    token_id: 11,
    background_color: '#2f7296',
    image_url: 'local::book.png',
    image_preview_url: null,
    image_thumbnail_url: null,
    image_original_url: null,
    name: 'Book',
    description: 'Book',
    asset_contract: {
      address: '0xdcf2a17bf95840bbe513ce2d9030bb03191570cf',
      name: 'Meme',
      symbol: 'MEME',
    },
    decimals: null,
    traits: [
      {
        trait_type: 'Level',
        value: 2,
        display_type: null,
        max_value: null,
        trait_count: 0,
        order: null,
      },
      {
        trait_type: 'Type',
        value: 'governance',
        display_type: null,
        max_value: null,
        trait_count: 4,
        order: null,
      },
      {
        trait_type: 'Vest Value',
        value: '1000',
        display_type: null,
        max_value: null,
        trait_count: 1,
        order: null,
      },
    ],
  },
  {
    id: 12,
    token_id: 12,
    background_color: '#7e8676',
    image_url: 'local::medal.png',
    image_preview_url: null,
    image_thumbnail_url: null,
    image_original_url: null,
    name: 'Medal',
    description: 'Medal',
    asset_contract: {
      address: '0xdcf2a17bf95840bbe513ce2d9030bb03191570cf',
      name: 'Meme',
      symbol: 'MEME',
    },
    decimals: null,
    traits: [
      {
        trait_type: 'Level',
        value: 3,
        display_type: null,
        max_value: null,
        trait_count: 0,
        order: null,
      },
      {
        trait_type: 'Type',
        value: 'governance',
        display_type: null,
        max_value: null,
        trait_count: 4,
        order: null,
      },
      {
        trait_type: 'Vest Value',
        value: '10000',
        display_type: null,
        max_value: null,
        trait_count: 1,
        order: null,
      },
    ],
  },
  {
    id: 13,
    token_id: 13,
    background_color: '#d1d1b0',
    image_url: 'local::pirate.png',
    image_preview_url: null,
    image_thumbnail_url: null,
    image_original_url: null,
    name: 'Pirate',
    description: 'Pirate',
    asset_contract: {
      address: '0xdcf2a17bf95840bbe513ce2d9030bb03191570cf',
      name: 'Meme',
      symbol: 'MEME',
    },
    decimals: null,
    traits: [
      {
        trait_type: 'Level',
        value: 1,
        display_type: null,
        max_value: null,
        trait_count: 0,
        order: null,
      },
      {
        trait_type: 'Type',
        value: 'timestamp',
        display_type: null,
        max_value: null,
        trait_count: 4,
        order: null,
      },
      {
        trait_type: 'Vest Value',
        value: '100',
        display_type: null,
        max_value: null,
        trait_count: 1,
        order: null,
      },
    ],
  },
  {
    id: 14,
    token_id: 14,
    background_color: '#906450',
    image_url: 'local::yonko.png',
    image_preview_url: null,
    image_thumbnail_url: null,
    image_original_url: null,
    name: 'Yonko',
    description: 'Yonko',
    asset_contract: {
      address: '0xdcf2a17bf95840bbe513ce2d9030bb03191570cf',
      name: 'Meme',
      symbol: 'MEME',
    },
    decimals: null,
    traits: [
      {
        trait_type: 'Level',
        value: 2,
        display_type: null,
        max_value: null,
        trait_count: 0,
        order: null,
      },
      {
        trait_type: 'Type',
        value: 'timestamp',
        display_type: null,
        max_value: null,
        trait_count: 4,
        order: null,
      },
      {
        trait_type: 'Vest Value',
        value: '1000',
        display_type: null,
        max_value: null,
        trait_count: 1,
        order: null,
      },
    ],
  },
  {
    id: 15,
    token_id: 15,
    background_color: '#6b3822',
    image_url: 'local::one-piece.png',
    image_preview_url: null,
    image_thumbnail_url: null,
    image_original_url: null,
    name: 'One Piece',
    description: 'One Piece',
    asset_contract: {
      address: '0xdcf2a17bf95840bbe513ce2d9030bb03191570cf',
      name: 'Meme',
      symbol: 'MEME',
    },
    decimals: null,
    traits: [
      {
        trait_type: 'Level',
        value: 3,
        display_type: null,
        max_value: null,
        trait_count: 0,
        order: null,
      },
      {
        trait_type: 'Type',
        value: 'timestamp',
        display_type: null,
        max_value: null,
        trait_count: 4,
        order: null,
      },
      {
        trait_type: 'Vest Value',
        value: '10000',
        display_type: null,
        max_value: null,
        trait_count: 1,
        order: null,
      },
    ],
  },
  {
    id: 16,
    token_id: 16,
    background_color: '#827d9a',
    image_url: 'local::smoke-fruit.png',
    image_preview_url: null,
    image_thumbnail_url: null,
    image_original_url: null,
    name: 'Smoke Fruit',
    description: 'Smoke Fruit',
    asset_contract: {
      address: '0xdcf2a17bf95840bbe513ce2d9030bb03191570cf',
      name: 'Meme',
      symbol: 'MEME',
    },
    decimals: null,
    traits: [
      {
        trait_type: 'Level',
        value: 1,
        display_type: null,
        max_value: null,
        trait_count: 0,
        order: null,
      },
      {
        trait_type: 'Type',
        value: 'game',
        display_type: null,
        max_value: null,
        trait_count: 4,
        order: null,
      },
      {
        trait_type: 'Vest Value',
        value: '100',
        display_type: null,
        max_value: null,
        trait_count: 1,
        order: null,
      },
    ],
  },
  {
    id: 17,
    token_id: 17,
    background_color: '#b6a879',
    image_url: 'local::sand-fruit.png',
    image_preview_url: null,
    image_thumbnail_url: null,
    image_original_url: null,
    name: 'Sand-Sand Fruit',
    description: 'Sand-Sand Fruit',
    asset_contract: {
      address: '0xdcf2a17bf95840bbe513ce2d9030bb03191570cf',
      name: 'Meme',
      symbol: 'MEME',
    },
    decimals: null,
    traits: [
      {
        trait_type: 'Level',
        value: 2,
        display_type: null,
        max_value: null,
        trait_count: 0,
        order: null,
      },
      {
        trait_type: 'Type',
        value: 'game',
        display_type: null,
        max_value: null,
        trait_count: 4,
        order: null,
      },
      {
        trait_type: 'Vest Value',
        value: '1000',
        display_type: null,
        max_value: null,
        trait_count: 1,
        order: null,
      },
    ],
  },
  {
    id: 18,
    token_id: 18,
    background_color: '#9e4052',
    image_url: 'local::mera-fruit.png',
    image_preview_url: null,
    image_thumbnail_url: null,
    image_original_url: null,
    name: 'Mera-Mera Fruit',
    description: 'Mera-Mera Fruit',
    asset_contract: {
      address: '0xdcf2a17bf95840bbe513ce2d9030bb03191570cf',
      name: 'Meme',
      symbol: 'MEME',
    },
    decimals: null,
    traits: [
      {
        trait_type: 'Level',
        value: 3,
        display_type: null,
        max_value: null,
        trait_count: 0,
        order: null,
      },
      {
        trait_type: 'Type',
        value: 'game',
        display_type: null,
        max_value: null,
        trait_count: 4,
        order: null,
      },
      {
        trait_type: 'Vest Value',
        value: '10000',
        display_type: null,
        max_value: null,
        trait_count: 1,
        order: null,
      },
    ],
  },
  // 新增 identity
  {
    id: 19,
    token_id: 19,
    background_color: '#A42741',
    image_url: 'local::hawkeye.png',
    image_preview_url: null,
    image_thumbnail_url: null,
    image_original_url: null,
    name: 'Hawkeye',
    description: 'Hawkeye',
    asset_contract: {
      address: '0xdcf2a17bf95840bbe513ce2d9030bb03191570cf',
      name: 'Meme',
      symbol: 'MEME',
    },
    decimals: null,
    traits: [
      {
        trait_type: 'Level',
        value: 1,
        display_type: null,
        max_value: null,
        trait_count: 0,
        order: null,
      },
      {
        trait_type: 'Type',
        value: 'identity',
        display_type: null,
        max_value: null,
        trait_count: 4,
        order: null,
      },
      {
        trait_type: 'Vest Value',
        value: '100',
        display_type: null,
        max_value: null,
        trait_count: 1,
        order: null,
      },
    ],
  },
  {
    id: 20,
    token_id: 20,
    background_color: '#614F67',
    image_url: 'local::bear.png',
    image_preview_url: null,
    image_thumbnail_url: null,
    image_original_url: null,
    name: 'Bear',
    description: 'Bear',
    asset_contract: {
      address: '0xdcf2a17bf95840bbe513ce2d9030bb03191570cf',
      name: 'Meme',
      symbol: 'MEME',
    },
    decimals: null,
    traits: [
      {
        trait_type: 'Level',
        value: 2,
        display_type: null,
        max_value: null,
        trait_count: 0,
        order: null,
      },
      {
        trait_type: 'Type',
        value: 'identity',
        display_type: null,
        max_value: null,
        trait_count: 4,
        order: null,
      },
      {
        trait_type: 'Vest Value',
        value: '1000',
        display_type: null,
        max_value: null,
        trait_count: 1,
        order: null,
      },
    ],
  },
  {
    id: 21,
    token_id: 21,
    background_color: '#4790D9',
    image_url: 'local::jinbei.png',
    image_preview_url: null,
    image_thumbnail_url: null,
    image_original_url: null,
    name: 'Jinbei',
    description: 'Jinbei',
    asset_contract: {
      address: '0xdcf2a17bf95840bbe513ce2d9030bb03191570cf',
      name: 'Meme',
      symbol: 'MEME',
    },
    decimals: null,
    traits: [
      {
        trait_type: 'Level',
        value: 3,
        display_type: null,
        max_value: null,
        trait_count: 0,
        order: null,
      },
      {
        trait_type: 'Type',
        value: 'identity',
        display_type: null,
        max_value: null,
        trait_count: 4,
        order: null,
      },
      {
        trait_type: 'Vest Value',
        value: '10000',
        display_type: null,
        max_value: null,
        trait_count: 1,
        order: null,
      },
    ],
  },
  // 新增 referral
  {
    id: 22,
    token_id: 22,
    background_color: '#A42741',
    image_url: 'local::sengohu.png',
    image_preview_url: null,
    image_thumbnail_url: null,
    image_original_url: null,
    name: 'Sengohu',
    description: 'Sengohu',
    asset_contract: {
      address: '0xdcf2a17bf95840bbe513ce2d9030bb03191570cf',
      name: 'Meme',
      symbol: 'MEME',
    },
    decimals: null,
    traits: [
      {
        trait_type: 'Level',
        value: 1,
        display_type: null,
        max_value: null,
        trait_count: 0,
        order: null,
      },
      {
        trait_type: 'Type',
        value: 'referral',
        display_type: null,
        max_value: null,
        trait_count: 4,
        order: null,
      },
      {
        trait_type: 'Vest Value',
        value: '100',
        display_type: null,
        max_value: null,
        trait_count: 1,
        order: null,
      },
    ],
  },
  {
    id: 23,
    token_id: 23,
    background_color: '#614F67',
    image_url: 'local::grrp.png',
    image_preview_url: null,
    image_thumbnail_url: null,
    image_original_url: null,
    name: 'Grrp',
    description: 'Grrp',
    asset_contract: {
      address: '0xdcf2a17bf95840bbe513ce2d9030bb03191570cf',
      name: 'Meme',
      symbol: 'MEME',
    },
    decimals: null,
    traits: [
      {
        trait_type: 'Level',
        value: 2,
        display_type: null,
        max_value: null,
        trait_count: 0,
        order: null,
      },
      {
        trait_type: 'Type',
        value: 'referral',
        display_type: null,
        max_value: null,
        trait_count: 4,
        order: null,
      },
      {
        trait_type: 'Vest Value',
        value: '1000',
        display_type: null,
        max_value: null,
        trait_count: 1,
        order: null,
      },
    ],
  },
  {
    id: 24,
    token_id: 24,
    background_color: '#4790D9',
    image_url: 'local::issho.png',
    image_preview_url: null,
    image_thumbnail_url: null,
    image_original_url: null,
    name: 'Issho',
    description: 'Issho',
    asset_contract: {
      address: '0xdcf2a17bf95840bbe513ce2d9030bb03191570cf',
      name: 'Meme',
      symbol: 'MEME',
    },
    decimals: null,
    traits: [
      {
        trait_type: 'Level',
        value: 3,
        display_type: null,
        max_value: null,
        trait_count: 0,
        order: null,
      },
      {
        trait_type: 'Type',
        value: 'referral',
        display_type: null,
        max_value: null,
        trait_count: 4,
        order: null,
      },
      {
        trait_type: 'Vest Value',
        value: '10000',
        display_type: null,
        max_value: null,
        trait_count: 1,
        order: null,
      },
    ],
  },
]
